language: go
go:
  - 1.9
env:
  - DEP_VERSION="0.4.1"
before_install:
  - curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64 -o $GOPATH/bin/dep
  - chmod +x $GOPATH/bin/dep
  # TODO: Run tests on CI (requires synapse)
install:
  - dep ensure
script:
  - go build -o terraform-provider-matrix
