dist: trusty
language: go
go:
  - 1.9
env:
  # We want to make sure we have as much information as possible when the tests explode
  - DEP_VERSION="0.4.1" TF_LOG=DEBUG
services:
  - docker
before_install:
  - curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64 -o $GOPATH/bin/dep
  - chmod +x $GOPATH/bin/dep
install:
  - dep ensure -v
  - docker build -t terraform-provider-matrix-tests .
script:
  - docker run --rm --name terraform-provider-matrix-tests terraform-provider-matrix-tests
  - go build -o terraform-provider-matrix
