version: 2
jobs:
  build_linux_amd64:
    environment:
      - ARCH: linux-amd64
      - GOARCH: amd64
    docker:
      - image: circleci/golang:1.12
    working_directory: /go/github.com/turt2live/terraform-provider-matrix
    steps:
      - checkout
      - run: go install -v ...
      - run: go vet
      - run: go build -o bin/terraform-provider-matrix-${ARCH}
      - store_artifacts:
          path: bin/
  build_linux_386:
    environment:
      - ARCH: linux-386
      - GOARCH: 386
    docker:
      - image: circleci/golang:1.12
    working_directory: /go/github.com/turt2live/terraform-provider-matrix
    steps:
      - checkout
      - run: go install -v ...
      - run: go vet
      - run: go build -o bin/terraform-provider-matrix-${ARCH}
      - store_artifacts:
          path: bin/
workflows:
  version: 2
  build_linux:
    jobs:
      - build_linux_amd64
      - build_linux_386
